### ISSUE TITLE
Browser window will maximize/restore when closing tabs too fast

### ISSUE THREAD

**Issue by CrescentMadeJr** [rxhanson/RectanglePro-Community#253]
Rectangle Pro: 2.8
MacOS 13.2.1

Using Firefox I have this issue when I have the "Double-click window title bar to maximize/restore" option checked.  When I close tabs in the browser too quickly by clicking the X on the tab, the action will trigger.

**Comment by rxhanson** [comment]
Thanks for reporting. This will be fixed in the next release, hopefully out by this weekend.

**Comment by rxhanson** [comment]
This should be fixed in v3.0+. Please reopen if it's not.

**Comment by CrescentMadeJr** [comment]
Still happening on v3.0.2 (143), Firefox.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
