### ISSUE TITLE
`left-half` action via URL is not working on v3.0.31

### ISSUE THREAD

**Issue by albertusdev** [rxhanson/RectanglePro-Community#559]
Somehow running the `left-half` cation (i.e `open -g rectangle-pro://execute-action?name=left-half`) doesn't work on the latest version.

What's weird is that the `right-half` counterpart works fine.

@rxhanson would you mind shedding some light into the issue, is it just a setup issue on my end or is this a known bug?

**Comment by rxhanson** [comment]
This is working fine for me. Perhaps you are just missing the quotations for that one?

```
open -g "rectangle-pro://execute-action?name=left-half"
```

**Comment by albertusdev** [comment]
@rxhanson ah sorry for the typo, I did execute it with quotations. The terminal doesn't log any error but I heard some sound playing when executing this action.

Do you have any suggestion on how to debug the issue further?

**Comment by rxhanson** [comment]
Next, let's see what the logs say. Hold the option key in the Rectangle Pro menu bar menu and select "View Logging...", then try the command.

**Comment by albertusdev** [comment]
@rxhanson thanks!

When trying to run `open -g "rectangle-pro://execute-action?name=left-half"` this got emitted on the logs:

`2024-09-17T18:08:17+07:00: Nil calculation result`

**Comment by albertusdev** [comment]
What's weird is that the free version of Rectangle doesn't have this bug, so I ended up reverting using the free and OSS version of Rectangle instead of the Rectangle Pro

**Comment by rxhanson** [comment]
Thanks for the follow up. I think I have this one figured out and will post back when the next release is out with a fix.

**Comment by rxhanson** [comment]
Sorry for the delay. Turns out I didn't have it figured out. Would you mind sending me your rectangle pro config? You can export it in the general tab of the settings window.

As a workaround until I get a fix out the door, you could still use Rectangle Pro by creating a custom shortcut and using the name you give it. You'd also have to add repeated actions to it if desired.

![image](https://github.com/user-attachments/assets/f36a6d44-0d4c-4f5e-bc7d-63798e873191)

```
 open -g "rectangle-pro://execute-custom?name=LeftHalf"
```

**Comment by albertusdev** [comment]
@rxhanson apologies for the delay! I just saw the latest version changelog on v3.0.36 (177) and seems like the bug has been fixed! Thank you so much. 

I also just discovered that there's a custom shortcut and it's able to be executed via deeplinks URL as well, this is super neat. Thank you for sharing this!

**Comment by 5HT2** [comment]
Thanks for following up!! I kind of assumed it was still broken lol, I'm glad it works now :)

https://github.com/user-attachments/assets/6b6424ba-02b4-4058-8bf8-c8dba66b1605
